id: P007841
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG01634
  title: གཏམ་སྐབས་ལྔ་པ་ལུང་དང་རིག་པའི་མེ་ཏོག་
  author: ''
  volumes:
    547e68f04d7e4140bfd3fdbdc84bb495:
      image_group_id: I00KG02927
      title: ''
      volume_number: 1
      total_pages: 42
ebook_metadata:
  title: གཏམ་སྐབས་ལྔ་པ་ལུང་དང་རིག་པའི་མེ་ཏོག་
  author: ''
  sku: P007841
  cover: cover.jpg
  layers:
  - pagination
