id: P007841
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 12:44:25.970214
source_metadata:
  id: bdr:W00KG01634
  title: གཏམ་སྐབས་ལྔ་པ་ལུང་དང་རིག་པའི་མེ་ཏོག་
  author: ''
  volumes:
    7a3b40502ed447a7b920415d06b91784:
      image_group_id: I00KG02927
      title: Volume 1 of gtam skabs lnga pa lung dang rig pa'i me tog
      volume_number: 1
      total_pages: 42
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
